### ISSUE TITLE
色々

### ISSUE THREAD

**Issue by sudahiroshi** [hidawafuwafu/ronbun#1]
1. TeXファイルもリポジトリに入れておきましょう．
2. まずは目次だけチェックします．
第2章　コーヒーについて
・アラビカ種のみ述べていますが，ロブスタ種については述べないのでしょうか？
第3章　抽出器具について
・どちらかと言うと，抽出方式があってこその抽出器具だと思います．なので，3章のタイトルは「抽出方法と抽出器具」にする方が妥当だと思います．または，3章のタイトルを「抽出方法について」に，各節を抽出方法の説明にして，節の中で抽出器具の項を作るぐらいでも良いと思います．
7章　本研究で開発するWebレシピの概要
・まずはコンセプトを書きましょう．

おまけ
・5章と6章と7.3はまとめた方が書きやすいかもしれません．

**Comment by sudahiroshi** [comment]
書き忘れ
第3章で取り扱っている抽出方法と抽出器具が少ないと思いますが，いかがでしょうか？
実際の成果物で取り扱っている種類は少なくても，論文としてまとめる際にはもっと多くても良いと思います．

**Comment by hidawafuwafu** [comment]
修正しました．

**Comment by sudahiroshi** [comment]
目次
2.2と2.3 アラビカ種とロブスタ種の起源が異なるのは分かるのですが，伝搬についても異なるものなのでしょうか？（別の節にしたほうが書きやすいならこのままで良いです）

本文
第1章
「私はこの度の研究に際して，コーヒーをテーマにした研究に興味を持った．」は，論文として不適切な表現なので削除してください．

あと，cloneしたらコンパイルできるように，必要なファイルもリポジトリに入れておいてください．

**Comment by hidawafuwafu** [comment]
目次に関して：生まれた国が違うので，伝搬的にも少し違うのですが，取り扱いたい話がアラビカ種主流の話（サードウェーブ・スペシャリティコーヒー）なので，正直書く必要があるか悩んでます．

本文に関して：承知しました

**Comment by sudahiroshi** [comment]
だとすると，コーヒー豆全体を説明する節にして，その中でちょっとだけでも良いのでロブスタ種を取り上げれば良いと思います．
元々，目次にアラビカ種だけ書いてあったことに違和感を感じました．まとめて説明すれば特に違和感は感じません．

**Comment by hidawafuwafu** [comment]
指摘の部分を修正しましたので確認お願いいたします．
おまけ程度にロブスタの話を本文に入れました．
